version: '3'

services:
  server1:
    build: .
    container_name: server1
    command: /app/server
    networks:
      - integration_network

  server2:
    build: .
    container_name: server2
    command: /app/server
    networks:
      - integration_network

  master:
    build: .
    container_name: master
    command: /app/master
    networks:
      - integration_network
    depends_on:
      - server1
      - server2

networks:
  integration_network:
    driver: bridge 
